spring:
  application:
    name: POS-SchoolShop-API
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:admin12345}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

cloudinary:
  cloud-name: daqwtec39
  api-key: 569271973363167
  api-secret: 8G5MkFUgyq7SgnjESZOqjnkp9ow